name: PLpgSQL Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PostgreSQL client
      run: sudo apt-get install postgresql-client

    - name: Wait for PostgreSQL
      run: until pg_isready --host=localhost --username=postgres --quiet; do sleep 1; done

    - name: Run tests
      run: |
        psql postgresql://postgres:postgres@localhost/testdb -f from_inaddr.sql
        psql postgresql://postgres:postgres@localhost/testdb -f tests/test_from_inaddr.sql
